[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
build = 'coc#util#install()'
hook_add = 'source ~/.config/nvim/coc-settings.vim'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'natebosch/vim-lsc'

[[plugins]]
repo = 'natebosch/vim-lsc-dart'
hook_source = 'let g:lsc_auto_map = v:true'

